export enum ActionStatus {
  Initial = 'init',
  Request = 'request',
  Success = 'success',
  Failure = 'fail',
}

export type FoodData = {
  'Food product': string;
  'Land use change': string;
  'Animal Feed': string;
  Farm: string;
  Processing: string;
  Transport: string;
  Packging: string;
  Retail: string;
};

export const LINK_LIST = [
  {
    link: '/blog',
    title: `BLOG LIST`,
    description: `Look around eco-friendly blog list!`,
  },
  {
    link: '/chart',
    title: `CHART`,
    description: `Check out the charts related to climate change!`,
  },
];

export const DEFAULT_IMAGE_1 = `/static/logo.jpg`;
export const DEFAULT_IMAGE_2 = `/static/og_image.png`;
export const sun_image = `/static/sun.png`;
export const moon_image = `/static/moon.png`;
export const favicon = `/static/favicon.ico`;

export const ogHeader = {
  title: `Better for`,
  description: `SAVE THE WORLD, SAVE THE YOURSELF.`,
  image: DEFAULT_IMAGE_2,
};

export const FOOD_CHART_AXIS_LABEL = {
  X: 'GHG Emissions per kg of food product',
  Y: 'Food Type',
};

export enum FOOD_CHART_DATA {
  'Food_product' = 'Food product',
  'Land_use_change' = 'Land use change',
  'Animal_Feed' = 'Animal Feed',
  Farm = 'Farm',
  Processing = 'Processing',
  Transport = 'Transport',
  Packging = 'Packging',
  Retail = 'Retail',
}

export const foodData = `Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,
Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,
Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,
Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,
Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,
Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,
Potatoes,0.0,0.0,0.2,0.0,0.1,0.0,0.0,
Cassava,0.6,0.0,0.2,0.0,0.1,0.0,0.0,
Cane Sugar,1.2,0.0,0.5,0.0,0.8,0.1,0.0,
Beet Sugar,0.0,0.0,0.5,0.2,0.6,0.1,0.0,
Other Pulses,0.0,0.0,1.1,0.0,0.1,0.4,0.0,
Peas,0.0,0.0,0.7,0.0,0.1,0.0,0.0,
Nuts,-2.1,0.0,2.1,0.0,0.1,0.1,0.0,
Groundnuts,0.4,0.0,1.4,0.4,0.1,0.1,0.0,
Soymilk,0.2,0.0,0.1,0.2,0.1,0.1,0.3,
Tofu,1.0,0.0,0.5,0.8,0.2,0.2,0.3,
Soybean Oil,3.1,0.0,1.5,0.3,0.3,0.8,0.0,
Palm Oil,3.1,0.0,2.1,1.3,0.2,0.9,0.0,
Sunflower Oil,0.1,0.0,2.1,0.2,0.2,0.9,0.0,
Rapeseed Oil,0.2,0.0,2.3,0.2,0.2,0.8,0.0,
Olive Oil,-0.4,0.0,4.3,0.7,0.5,0.9,0.0,
Tomatoes,0.4,0.0,0.7,0.0,0.2,0.1,0.0,
Onions & Leeks,0.0,0.0,0.2,0.0,0.1,0.0,0.0,
Root Vegetables,0.0,0.0,0.2,0.0,0.1,0.0,0.0,
Brassicas,0.0,0.0,0.3,0.0,0.1,0.0,0.0,
Other Vegetables,0.0,0.0,0.2,0.1,0.2,0.0,0.0,
Citrus Fruit,-0.1,0.0,0.3,0.0,0.1,0.0,0.0,
Bananas,0.0,0.0,0.3,0.1,0.3,0.1,0.0,
Apples,0.0,0.0,0.2,0.0,0.1,0.0,0.0,
Berries & Grapes,0.0,0.0,0.7,0.0,0.2,0.2,0.0,
Wine,-0.1,0.0,0.6,0.1,0.1,0.7,0.0,
Other Fruit,0.1,0.0,0.4,0.0,0.2,0.0,0.0,
Coffee,3.7,0.0,10.4,0.6,0.1,1.6,0.1,
Dark Chocolate,14.3,0.0,3.7,0.2,0.1,0.4,0.0,
Beef (beef herd),16.3,1.9,39.4,1.3,0.3,0.2,0.2,
Beef (dairy herd),0.9,2.5,15.7,1.1,0.4,0.3,0.2,
Lamb & Mutton,0.5,2.4,19.5,1.1,0.5,0.3,0.2,
Pig Meat,1.5,2.9,1.7,0.3,0.3,0.3,0.2,
Poultry Meat,2.5,1.8,0.7,0.4,0.3,0.2,0.2,
Milk,0.5,0.2,1.5,0.1,0.1,0.1,0.3,
Cheese,4.5,2.3,13.1,0.7,0.1,0.2,0.3,
Eggs,0.7,2.2,1.3,0.0,0.1,0.2,0.0,
Fish (farmed),0.5,0.8,3.6,0.0,0.1,0.1,0.0,
Shrimps (farmed),0.2,2.5,8.4,0.0,0.2,0.3,0.2,
`;

export const greenhouseGasData = [
  {
    title: 'Carbon Dioxide',
    desc:
      'Currently, most of the greenhouse gases generated by humans are carbon dioxide. Carbon dioxide is released into the atmosphere by various natural sources, and about 95% of the total carbon dioxide released would not have occurred if humans had not existed on Earth. For example, carbon dioxide generated by the natural decomposition of organic substances such as dead trees existing in forests and pastures is about 220 gigatons per year. This amount is about eight times the amount excreted by humans. Although most carbon dioxide is generated by natural sources, carbon dioxide from natural origin does not affect the recent increase in concentration. This is because the natural source is in balance with the natural absorption system that removes carbon dioxide from the atmosphere. The increase in carbon dioxide through the natural carbon cycle cannot explain the increase in atmospheric carbon dioxide concentrations of more than 3-4 gigatons per year over the decades after industrialization. Natural processes such as photosynthesis, exhalation, decay, and gas exchange processes on the surface of the sea are huge carbon cycle processes in natural systems such as the earth and the atmosphere, the ocean and the atmosphere. If human-generated carbon had not been absorbed by nearly half through the natural absorption system, the current concentration of carbon dioxide in the atmosphere would have increased exponentially. Radiant energy transmitted from the sun to the earth has a wide range of wavelengths, because carbon dioxide absorbs the wavelengths in the range of 2.5 to 3.0, 4 to 5, and 13 to 17 in the atmosphere. Carbon dioxide is generated when fossil fuels such as petroleum, natural gas, and coal are burned in factories or residential areas and added to the atmosphere, and also occurs when automobiles burn gasoline or when people incinerate garbage. The reason why carbon dioxide has the greatest effect on the greenhouse effect is not because this gas has an excellent ability to store thermal energy in the atmosphere. As a greenhouse gas, carbon dioxide has a weak effect on the greenhouse effect by about 20 times when compared to methane of the same concentration, but it is because it occupies more absolute amounts in the components of the atmosphere than other greenhouse gases. Carbon dioxide, which has rapidly increased in the atmosphere with industrialization, is the main cause of the increase due to excessive use of fossil fuels. When comparing coal and petroleum, which are mainly used as fuels, among these fossil fuels, coal emits more carbon dioxide than petroleum, and among coals, anthracite is composed of 92% carbon and emits the most carbon dioxide. Coal is not used as fuel for power engines such as automobiles, but the power generation method that still accounts for a large portion of power generation is thermal power generation, and the high proportion of coal as the fuel for this thermal power generation is very high. It becomes a problem. More than 75% of the increase in carbon dioxide concentration in the atmosphere after industrialization is due to the emission of carbon dioxide caused by factors such as cement manufacturing or the burning of fossil fuels. Another factor of increase stems from changes in land use, such as deforestation for agriculture. All of these changes are caused by human activity.',
  },
  {
    title: 'Methane',
    desc: `Methane as a greenhouse gas is 21 times stronger than carbon dioxide at the same concentration. The major natural sources of methane are wetlands, and additional natural sources include termites, oceans, plants, and methane hydrates. Methane is produced when organic matter is decomposed by microorganisms, and a significant amount of methane is released from fertilizers, rice paddies, garbage heaps, and even from the digestion of herbivores and insects. Also, methane is produced in the process of burning fossil fuels. Since the Industrial Revolution, the generation of methane has increased as human activities such as energy production from coal, natural gas, and waste discharge from landfills, increased breeding of ruminants such as cattle and sheep, rice farming and biomass burning, have increased. In addition, although it has not yet been clearly proven, several theories say the reason for the increase in methane. One of them is that the land in the tundra will be warmed by warming, releasing methane, and it can occur at the bottom of the sea. Once methane is released, it remains in the atmosphere for about 8.4 years before it is removed, mainly due to chemical oxidation in the troposphere.`,
  },
  {
    title: 'Water Vapor',
    desc: `Water vapor is the factor that has the greatest influence on the greenhouse effect. Water vapor absorbs infrared rays well and exists in a very large amount in the atmosphere. Water vapor by itself affects the greenhouse effect by about 36-66%, plus the effect of clouds by 66-85%. The concentration of water vapor is not constant depending on the region, and the change in water vapor concentration by humans is not very large except for small-scale regional influences. As the ambient temperature increases, the amount of water vapor that can be stored per unit volume increases. In other words, any kind of warming caused by an increase in the concentration of other greenhouse gases results in an increase in temperature resulting in an increase in the amount of water vapor per unit volume of the original gas. Therefore, the greenhouse effect due to water vapor is a natural function of the earth, but the concentration of water vapor in the atmosphere increases due to the increase in temperature due to the greenhouse gas, and thus it has a much larger effect than the greenhouse effect of water vapor performed by the original atmosphere. However, since water vapor can form clouds and reflect sunlight, the exact effect of water vapor on the greenhouse effect is not completely known. Also, there is currently no way to artificially control the amount of water vapor in the atmosphere.`,
  },
];

export const greenhouseEffect = [
  {
    title: 'Greenhouse Effect ☀️',
    desc:
      "The greenhouse effect caused by the actual atmosphere is a very important phenomenon that keeps the earth at a constant temperature. If there is no atmosphere and there is no greenhouse effect, Earth will receive sunlight during the day like Mars and rise more than tens of degrees, but on the contrary, at night without the sun, all heat will be released and fall below -100℃. In other words, the greenhouse effect is a phenomenon in which the atmosphere absorbs radiant energy emitted from the planet's surface so that it does not diffuse outward, and the temperature rises due to the energy. As such, the greenhouse effect is essential to the climate system and is not itself a problem. However, after the Industrial Revolution, the global warming phenomenon caused by excessive high temperatures caused by excessive emission of gases causing the greenhouse effect into the atmosphere becomes a problem.",
  },
  {
    title: 'Sea Level Rise 🌊',
    desc:
      "As temperatures rise, ice in the Arctic or Antarctica melts. If the temperature rises by about 3°C, most of the glaciers in the Arctic are floating icebergs, so even if they melt, sea level has no effect. However, as glaciers in Antarctica are continental glaciers, it is predicted that when they melt, sea level rises by about 7 m7 m. In that case, the actual submerged area along the coast of each continent is only about 3%, but considering that most of the world's big cities develop on the coast, and therefore, about a third of humanity lives in coastal areas. The disaster is enormous and adds to the seriousness of the problem. In other words, sea level has risen by an average of 10 to 20 cm over the past 20th century, and sea level rise is expected to continue in the future. If sea level rises significantly, there is a concern about damage from seawater flooding in countries with densely populated beaches, such as Bangladesh. Also, small island nations like Maldives will disappear. Thus, rising sea levels will pollute the water used by billions of people and cause large population migration.",
  },
  {
    title: 'Climate change ⛈',
    desc:
      "Climate change refers to the change over time in the global or regional climate of the Earth. Climate change may be due to internal or external forces (for example, changes in solar radiation), or human activity. According to recent studies, radiative forcing from greenhouse gases is a major cause of climate change. The temperature of the earth's surface has risen due to the greenhouse effect. This increase in temperature is becoming more pronounced toward higher northern latitudes. Also, the land shows a faster temperature rise than the ocean.",
  },
  {
    title: 'Global warming 🔥',
    desc:
      "Global warming is a long-term increase in the average temperature of the atmosphere and sea near the surface. Since the last industrial revolution, as greenhouse gases are continuously released into the atmosphere, the concentration of greenhouse gases in the earth's atmosphere increases, causing an excessive increase in the temperature of the earth's surface, resulting in such a global warming phenomenon. The rise in temperature on the earth's surface causes sea level rise, which in turn changes the amount and pattern of precipitation, causing extreme weather such as drought and flood. The retreat of glaciers and climate change threaten the survival of life on Earth, including humans, by changing ecosystems. Global warming has been progressing over recent decades [when?], and it is predicted to continue to increase in the future. It is not yet clear how much warming will take place in the future and how it will vary between regions.",
  },
  {
    title: 'Ecosystem and human impact 💥',
    desc:
      'The various global changes caused by the increase in greenhouse gases have a great impact on ecosystems and humans. Due to changes in the environment, the survival of the species is threatened and extinction is accelerated. Of course, species that adapt quickly to changes in temperature can survive through migration, but plant species cannot easily migrate. Thus, many plant species can become extinct. It also contributes to increased drought and forest fires. This is closely related not only to ecological problems but also to human food problems. Difficulties arise in cultivation of crops, and changes in marine ecosystems are caused by rising seawater temperatures. In addition, natural disasters such as heavy rains and storms, tsunamis and floods, droughts and forest fires cause loss of human life and property.',
  },
];

export const carbonFootPrint = {
  title: 'What is a Carbon Footprint? 🐾',
  desc:
    'A carbon footprint is the total amount of greenhouse gas emissions that come from the production, use and end-of-life of a product or service. It includes carbon dioxide — the gas most commonly emitted by humans — and others, including methane, nitrous oxide, and fluorinated gases, which trap heat in the atmosphere, causing global warming. Usually, the bulk of an individual’s carbon footprint will come from transportation, housing and food.',
};

export type Section = {
  title: string;
  desc: string;
  todolist?: string[];
};

export const section: Section[] = [
  {
    title: 'On the Road, in the Sky 🚲🚌',
    desc:
      'One of the most effective ways to begin thinking about how to reduce your carbon footprint is to reconsider how much, and how often, you travel. In November 2017 carbon dioxide emissions from transportation surpassed emissions from electricity generation as the top source of greenhouse gases. Why? Electricity generation is shifting away from the use of coal to more renewable sources and natural gas. But let’s be realistic. You will likely need to use a car this year. So, when you do, here are some tips to make your trip more climate-friendly',
    todolist: [
      'Go easy on the gas and brakes — driving efficiently can help to reduce emissions. Drive “like you have an egg under your foot,” recommends Brian West, an expert in fuel and engine research from the Oak Ridge National Laboratory.',
      'Regularly service your car to keep it more efficient.',
      'Check your tires. Keeping tires pumped correctly can reduce emissions. “Low tire pressure will hurt your fuel economy”',
      'Air conditioning and intensive city driving can make emissions creep up. Cut down on these as often as possible.',
      'Use cruise control on long drives — in most cases, this can help to save gas.',
      'Don’t weigh your car down with extra things that you don’t need on your trip.',
      'Carpool — this way, you’re splitting emissions between the number of people in the car.',
      'Cars with lower emissions can often end up costing less to operate.',
    ],
  },
  {
    title: 'On your Plate 🥣',
    desc: 'Globally, emissions are linked to what we put on our plates.',
    todolist: [
      'While food systems are complicated, and research is still evolving on what the most environmentally-friendly diet is, experts mostly agree that cutting down on meat, and red meat in particular, is a better choice for the environment. This is because the production of red meat uses a lot of feed, water and land. Cows themselves also give off methane emissions (a harmful greenhouse gas).',
      'For that reason, eating a vegan diet is likely to be best for the environment, say experts. According to a study published in 2017 in the journal Environmental Research Letters, red meat can have up to 100 times the environmental impact of plant based food. (According to some estimates, beef gives off more than six pounds of carbon dioxide per serving; the amount created per serving by rice, legumes carrots, apples or potatoes is less than half a pound.)',
      'Eating a vegetarian or pescetarian diet are also likely to be better for the environment than a diet which includes a lot of meat. Each of these, however, depend on exactly what you are eating, and how much of it. If you replace that meat with dairy, for example, your emissions could rise again. “Deep net fishing can emit as much as beef,” said Marco Springmann, a senior researcher on environmental sustainability and public health at the University of Oxford. Following national health guidelines, with further reductions in meat, fish and dairy (this is similar to a Mediterranean diet) is a good option too, Dr. Springmann said. These diets can also have health benefits.',
      'Overall, eating low down the food chain as often as you can is a probably a good way to reduce your carbon footprint and stay healthy, say experts. That means filling your plate with vegetables, fruits, grains and beans. For meat-lovers, even swapping carbon-intensive meats like beef and lamb with chicken can make a difference. Better still, swap a few meals per-week to vegan or vegetarian.',
    ],
  },
  {
    title: 'In your Home 🏡',
    desc:
      'There are simple changes you can make at home that will save you energy, and money.',
    todolist: [
      'Turn down the heat. Use a programmable or smart thermostat, if you have one. Keep blinds closed to help keep temperature stable inside.',
      'Turn off lights and appliances when you’re not using them. Turn off appliances at the power outlet to reduce even more energy. Putting them to sleep is second best.',
      'Stream movies through your smart TV, not your game console. Smart TVs and their plugins use just a few watts to stream movies, Mr. Horowitz said, but if you use your game console, energy use is about 10 times higher, because they aren’t optimized to play films.',
      'Buy a laptop, not a desktop computer. Laptops take less energy to charge and run.',
      'Replace lights. LED lights use up to 85 percent less energy, last up to 25 times longer and are cheaper to run than incandescent lights.',
      'Replace old fridges.They are “energy hogs” according to Mr. Horowitz, and can cost you up to $100 extra per year to run. “If it’s 15 to 20 years old,” he said, “it’s a no brainer to recycle it.”',
    ],
  },
  {
    title: 'What you Buy 🛒',
    desc:
      'Buying less is the first step. Beyond that, there are simple ways to reduce the impact from your purchases. According to the World Resources Institute, 20 items of clothing are manufactured per person, per year. This is because of “fast fashion”: clothes that are produced quickly, cheaply and unsustainably. As the price of our clothes drops, the environmental (and human) costs increase.',
    todolist: [
      'Look for a fairtrade, or similar logo. This indicates your clothes were made sustainably.',
      'Shop vintage. You’ll be saving money, and the environment.',
      'Don’t buy clothing that will either wear out quickly, or, that you’ll barely wear.',
      'Consider the fabric. Different materials have different environmental impacts',
      'Donate old clothes.',
      'Buying less and wearing more',
    ],
  },
];

export const refLink =
  'https://www.nytimes.com/guides/year-of-living-better/how-to-reduce-your-carbon-footprint';

export const wikiLink =
  'https://ko.wikipedia.org/wiki/%EC%98%A8%EC%8B%A4_%EA%B8%B0%EC%B2%B4';
