export enum ActionStatus {
  Initial = 'init',
  Request = 'request',
  Success = 'success',
  Failure = 'fail'
}

export type FoodData = {
  'Food product': string;
  'Land use change': string;
  'Animal Feed': string;
  Farm: string;
  Processing: string;
  Transport: string;
  Packging: string;
  Retail: string;
};

export const LINK_LIST = [
  {
    link: '/blog',
    title: `BLOG LIST`,
    // description: `How about looking for a better life on your eco-friendly blog?`,
    description: `Look around eco-friendly blog list!`
  },
  {
    link: '/chart',
    title: `CHART`,
    // description: `How about looking for a better life on your eco-friendly blog?`,
    description: `Check out the charts related to climate change!`
  }
];

export const DEFAULT_IMAGE_1 = `/static/logo.jpg`;
export const DEFAULT_IMAGE_2 = `/static/og_image.png`;
export const sun_image = `/static/sun.png`;
export const moon_image = `/static/moon.png`;
export const favicon = `/static/favicon.ico`;

export const ogHeader = {
  title: `Better for`,
  description: `SAVE THE WORLD, SAVE THE YOURSELF.`,
  image: DEFAULT_IMAGE_2
};

export const foodChartAxisLabel = {
  X: 'GHG Emissions per kg of food product',
  Y: 'Food Type'
};

export enum foodChartData {
  'Food_product' = 'Food product',
  'Land_use_change' = 'Land use change',
  'Animal_Feed' = 'Animal Feed',
  Farm = 'Farm',
  Processing = 'Processing',
  Transport = 'Transport',
  Packging = 'Packging',
  Retail = 'Retail'
}

export const foodData = `Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,
Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,
Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,
Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,
Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,
Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,
Potatoes,0.0,0.0,0.2,0.0,0.1,0.0,0.0,
Cassava,0.6,0.0,0.2,0.0,0.1,0.0,0.0,
Cane Sugar,1.2,0.0,0.5,0.0,0.8,0.1,0.0,
Beet Sugar,0.0,0.0,0.5,0.2,0.6,0.1,0.0,
Other Pulses,0.0,0.0,1.1,0.0,0.1,0.4,0.0,
Peas,0.0,0.0,0.7,0.0,0.1,0.0,0.0,
Nuts,-2.1,0.0,2.1,0.0,0.1,0.1,0.0,
Groundnuts,0.4,0.0,1.4,0.4,0.1,0.1,0.0,
Soymilk,0.2,0.0,0.1,0.2,0.1,0.1,0.3,
Tofu,1.0,0.0,0.5,0.8,0.2,0.2,0.3,
Soybean Oil,3.1,0.0,1.5,0.3,0.3,0.8,0.0,
Palm Oil,3.1,0.0,2.1,1.3,0.2,0.9,0.0,
Sunflower Oil,0.1,0.0,2.1,0.2,0.2,0.9,0.0,
Rapeseed Oil,0.2,0.0,2.3,0.2,0.2,0.8,0.0,
Olive Oil,-0.4,0.0,4.3,0.7,0.5,0.9,0.0,
Tomatoes,0.4,0.0,0.7,0.0,0.2,0.1,0.0,
Onions & Leeks,0.0,0.0,0.2,0.0,0.1,0.0,0.0,
Root Vegetables,0.0,0.0,0.2,0.0,0.1,0.0,0.0,
Brassicas,0.0,0.0,0.3,0.0,0.1,0.0,0.0,
Other Vegetables,0.0,0.0,0.2,0.1,0.2,0.0,0.0,
Citrus Fruit,-0.1,0.0,0.3,0.0,0.1,0.0,0.0,
Bananas,0.0,0.0,0.3,0.1,0.3,0.1,0.0,
Apples,0.0,0.0,0.2,0.0,0.1,0.0,0.0,
Berries & Grapes,0.0,0.0,0.7,0.0,0.2,0.2,0.0,
Wine,-0.1,0.0,0.6,0.1,0.1,0.7,0.0,
Other Fruit,0.1,0.0,0.4,0.0,0.2,0.0,0.0,
Coffee,3.7,0.0,10.4,0.6,0.1,1.6,0.1,
Dark Chocolate,14.3,0.0,3.7,0.2,0.1,0.4,0.0,
Beef (beef herd),16.3,1.9,39.4,1.3,0.3,0.2,0.2,
Beef (dairy herd),0.9,2.5,15.7,1.1,0.4,0.3,0.2,
Lamb & Mutton,0.5,2.4,19.5,1.1,0.5,0.3,0.2,
Pig Meat,1.5,2.9,1.7,0.3,0.3,0.3,0.2,
Poultry Meat,2.5,1.8,0.7,0.4,0.3,0.2,0.2,
Milk,0.5,0.2,1.5,0.1,0.1,0.1,0.3,
Cheese,4.5,2.3,13.1,0.7,0.1,0.2,0.3,
Eggs,0.7,2.2,1.3,0.0,0.1,0.2,0.0,
Fish (farmed),0.5,0.8,3.6,0.0,0.1,0.1,0.0,
Shrimps (farmed),0.2,2.5,8.4,0.0,0.2,0.3,0.2,
`;

export const greenhouseGasData = [
  {
    title: 'Carbon Dioxide',
    desc:
      'Currently, most of the greenhouse gases generated by humans are carbon dioxide. Carbon dioxide is released into the atmosphere by various natural sources, and about 95% of the total carbon dioxide released would not have occurred if humans had not existed on Earth. For example, carbon dioxide generated by the natural decomposition of organic substances such as dead trees existing in forests and pastures is about 220 gigatons per year. This amount is about eight times the amount excreted by humans. Although most carbon dioxide is generated by natural sources, carbon dioxide from natural origin does not affect the recent increase in concentration. This is because the natural source is in balance with the natural absorption system that removes carbon dioxide from the atmosphere. The increase in carbon dioxide through the natural carbon cycle cannot explain the increase in atmospheric carbon dioxide concentrations of more than 3-4 gigatons per year over the decades after industrialization. Natural processes such as photosynthesis, exhalation, decay, and gas exchange processes on the surface of the sea are huge carbon cycle processes in natural systems such as the earth and the atmosphere, the ocean and the atmosphere. If human-generated carbon had not been absorbed by nearly half through the natural absorption system, the current concentration of carbon dioxide in the atmosphere would have increased exponentially. Radiant energy transmitted from the sun to the earth has a wide range of wavelengths, because carbon dioxide absorbs the wavelengths in the range of 2.5 to 3.0, 4 to 5, and 13 to 17 in the atmosphere. Carbon dioxide is generated when fossil fuels such as petroleum, natural gas, and coal are burned in factories or residential areas and added to the atmosphere, and also occurs when automobiles burn gasoline or when people incinerate garbage. The reason why carbon dioxide has the greatest effect on the greenhouse effect is not because this gas has an excellent ability to store thermal energy in the atmosphere. As a greenhouse gas, carbon dioxide has a weak effect on the greenhouse effect by about 20 times when compared to methane of the same concentration, but it is because it occupies more absolute amounts in the components of the atmosphere than other greenhouse gases. Carbon dioxide, which has rapidly increased in the atmosphere with industrialization, is the main cause of the increase due to excessive use of fossil fuels. When comparing coal and petroleum, which are mainly used as fuels, among these fossil fuels, coal emits more carbon dioxide than petroleum, and among coals, anthracite is composed of 92% carbon and emits the most carbon dioxide. Coal is not used as fuel for power engines such as automobiles, but the power generation method that still accounts for a large portion of power generation is thermal power generation, and the high proportion of coal as the fuel for this thermal power generation is very high. It becomes a problem. More than 75% of the increase in carbon dioxide concentration in the atmosphere after industrialization is due to the emission of carbon dioxide caused by factors such as cement manufacturing or the burning of fossil fuels. Another factor of increase stems from changes in land use, such as deforestation for agriculture. All of these changes are caused by human activity.'
  },
  {
    title: 'Methane',
    desc: `Methane as a greenhouse gas is 21 times stronger than carbon dioxide at the same concentration. The major natural sources of methane are wetlands, and additional natural sources include termites, oceans, plants, and methane hydrates. Methane is produced when organic matter is decomposed by microorganisms, and a significant amount of methane is released from fertilizers, rice paddies, garbage heaps, and even from the digestion of herbivores and insects. Also, methane is produced in the process of burning fossil fuels. Since the Industrial Revolution, the generation of methane has increased as human activities such as energy production from coal, natural gas, and waste discharge from landfills, increased breeding of ruminants such as cattle and sheep, rice farming and biomass burning, have increased. In addition, although it has not yet been clearly proven, several theories say the reason for the increase in methane. One of them is that the land in the tundra will be warmed by warming, releasing methane, and it can occur at the bottom of the sea. Once methane is released, it remains in the atmosphere for about 8.4 years before it is removed, mainly due to chemical oxidation in the troposphere.`
  },
  {
    title: 'Water Vapor',
    desc: `Water vapor is the factor that has the greatest influence on the greenhouse effect. Water vapor absorbs infrared rays well and exists in a very large amount in the atmosphere. Water vapor by itself affects the greenhouse effect by about 36-66%, plus the effect of clouds by 66-85%. The concentration of water vapor is not constant depending on the region, and the change in water vapor concentration by humans is not very large except for small-scale regional influences. As the ambient temperature increases, the amount of water vapor that can be stored per unit volume increases. In other words, any kind of warming caused by an increase in the concentration of other greenhouse gases results in an increase in temperature resulting in an increase in the amount of water vapor per unit volume of the original gas. Therefore, the greenhouse effect due to water vapor is a natural function of the earth, but the concentration of water vapor in the atmosphere increases due to the increase in temperature due to the greenhouse gas, and thus it has a much larger effect than the greenhouse effect of water vapor performed by the original atmosphere. However, since water vapor can form clouds and reflect sunlight, the exact effect of water vapor on the greenhouse effect is not completely known. Also, there is currently no way to artificially control the amount of water vapor in the atmosphere.`
  }
];

//example
// export const SAMPLE_DATA = [
//   {
//     link: 'https://yeun.github.io/open-color/',
//     h3: `Check color`,
//     p: `We have to find own symbolic color.`
//   },
//   {
//     link: 'https://www.iucn.org/',
//     h3: `Conserves nature`,
//     p: `A just world that values and conserves nature.`
//   },
//   {
//     link: 'https://css-tricks.com/',
//     h3: `Check css-tricks`,
//     p: `We can improve css skill!`
//   }
// ];

// export const ECO_FRIENDLY_BLOGS = [
//   {
//     title: 'Earth911',
//     url: 'https://earth911.com/',
//     image:
//       'https://23pxcp3u31lgiybw92v8rma1-wpengine.netdna-ssl.com/wp-content/uploads/2015/05/logo.png',
//     description:
//       'deAt Earth911, We’ve Created A Community That Helps People Find Their Own Shade Of Green, Match Their Values To Their Purchase Behaviors, Adopt Environmentally Sound Practices And Drive Impactful Environmental Changes. We Are Dedicated To Increasing Recycling Rates And Helping You Choose Sustainable Options To Live A Happier, Healthier Lifestyle; One That Protects This Wonderful Planet We Call Earth.scription',
//     id: 0
//   },
//   {
//     title: 'Treehugger',
//     url: 'https://www.treehugger.com/',
//     image: null,
//     description:
//       'Local or organic? Hybrid or electric? Paper or plastic or neither? Nearly all decisions today affect the environment, and figuring out which choices matter most often feels impossible. That’s why we made Treehugger, the only modern sustainability site that offers advice, clarity, and inspiration for both the eco-savvy and the green living novice. With more than 120 million readers each year, Treehugger is the world’s largest information site dedicated to driving sustainability mainstream.',
//     id: 1
//   },
//   {
//     title: 'ecocult',
//     url: 'https://ecocult.com/',
//     image:
//       'https://cdn.shortpixel.ai/client/q_glossy,ret_img/https://ecocult.com/wp-content/themes/AF-Theme-Ecocult/Images/Logo-Header.png',
//     description:
//       'EcoCult is a curious, thoughtful, science-based view into the international sustainable fashion industry.',
//     id: 2
//   },
//   {
//     title: 'eco warrior princess',
//     url: 'https://ecowarriorprincess.net/',
//     image:
//       'https://1yjob743ilegfihp83lnmdm1-wpengine.netdna-ssl.com/wp-content/uploads/2018/05/logo.png',
//     description:
//       'Eco Warrior Princess is a media brand that is redefining what it means to live green. Founded in 2010 by Jennifer Nini a writer, activist and certified organic farm owner, Eco Warrior Princess covers the topics that matter — environmental issues, conservation, sustainable fashion, conscious business, social justice, politics, feminism, eco beauty, wellness, green technology — in an analytical, intelligent and honest way – without any of the BS. Eco Warrior Princess isn’t just a platform. Or even a publication. It’s a media business and a community of clever, stylish, discerning people who want to be part of the solution, not part of the problem. We’re moving beyond the granola-hippie cliche and dismantling ethical elitism, to bring you media that matters. Today, Eco Warrior Princess continues to grow, leveraging a small network of passionate writers and industry experts from around the world to cover the latest in green intelligence.',
//     id: 3
//   },
//   {
//     title: 'eco hustler',
//     url: 'https://ecohustler.com/',
//     image: null,
//     description:
//       'Ecohustler is an independent online magazine with a global reach of millions. Our mission is to bring people unexpected, entertaining, ecological content with a focus on connecting with nature and each other, so that we can all become a part of the solution to environmental breakdown.',
//     id: 4
//   },
//   {
//     title: 'going zero waste',
//     url: 'https://goingzerowaste.com/',
//     image:
//       'https://cdn.statically.io/img/goingzerowaste.com/wp-content/uploads/2020/04/Header2.jpg?w=800&f=auto',
//     description:
//       'We aim to send nothing to a landfill. We reduce what we need, reuse as much as we can, send little to be recycled, and compost what we cannot. The less simple answer: It’s really about redefining the system. We currently live in a linear economy where we take resources from the earth and then dump them in a giant hole in the ground. The goal of zero waste is to move to a circular economy where we write trash out of existence. The circular economy mimics nature in that there is no trash in nature.',
//     id: 5
//   },
//   {
//     title: 'dr.karens lee',
//     url: 'https://www.drkarenslee.com/',
//     image:
//       'https://www.drkarenslee.com/wp-content/uploads/2020/05/DKLmobile_400.png',
//     description:
//       'After much deliberation, I decided to create this site to share my knowledge and build a community of like-minded people who care about prevention and not sickness. Learning what to eat and what to avoid is very challenging in this busy times. But as cliché as it might sound, you are what you eat. And food can be medicine or poison. I can help you find solutions for your food-related conditions and recommend special diets, products, supplements, meal plans and the support to help you. We can solve the mystery together.',
//     id: 6
//   },
//   {
//     title: 'get green be well',
//     url: 'https://www.getgreenbewell.com/',
//     image:
//       'https://www.getgreenbewell.com/wp-content/uploads/2020/04/GGBW-Logo-Web_Test2.jpeg',
//     description:
//       'Get Green Be Well is founded by Kimberly Button, a certified WELL AP, green living expert, professional journalist, author, TV correspondent, speaker, editor and award-winning photographer. Kimberly Button is the author of The Ultimate Home Detox Guide, The Everything Guide to a Healthy Home (Adams Media), green living columnist for Vibrant Life magazine, and creator of the Orlando Green Travel app (Sutro Media).',
//     id: 7
//   },
//   {
//     title: 'bio friendly planet',
//     url: 'https://biofriendlyplanet.com/',
//     image:
//       'https://biofriendlyplanet.com/wp-content/uploads/2017/06/bpm-logo.jpg',
//     description:
//       'There are a lot of magazines, websites and groups that discuss the problems we face because of environmental pollution. While many of the same stories that those groups cover are shared here for reference, this is not another one of those websites. This magazine is a place for people who want simple ways to actively make this planet greener and who are tired of the doom and gloom reporting on the environment.',
//     id: 8
//   },
//   {
//     title: 'eco ideaz',
//     url: 'https://www.ecoideaz.com/',
//     image:
//       'https://www.ecoideaz.com/wp-content/uploads/2015/07/ecoideaz_logo.png',
//     description:
//       'Ecoideaz evolved from the need to fill the gap in spreading awareness about sustainable technologies to become a platform for bringing together people and organisations who are effective catalysts for the much needed change that will ensure the well being of planet earth and all its elements.',
//     id: 9
//   },
//   {
//     title: 'gypsy soul',
//     url: 'https://www.gypsysoul.co.uk/',
//     image:
//       'https://www.gypsysoul.co.uk/wp-content/uploads/2018/12/cropped-Gypsy-soul-blog-header-4.png',
//     description:
//       'Our ultimate aim was to minimize, simplify and just enjoy life more. It has been a hard and long process but we finally feel like we’ve got to where we want to be.',
//     id: 10
//   },
//   {
//     title: 'the zero waste collective',
//     url: 'https://www.thezerowastecollective.com/',
//     image: null,
//     description:
//       'With an engaged and supportive online community, The Zero Waste Collective educates and inspires people worldwide to live more sustainably by reducing their waste. What does The Zero Waste Collective envision for the future? A world without waste. How will we get there? One imperfect step at a time, together, in an encouraging environment.',
//     id: 11
//   }
// ];
